
export default {
    SET_DIRECTION: 'SET_DIRECTION',
    SET_THROTTLE: 'SET_THROTTLE',
    TURN_LEFT: 'TURN_LEFT',
    TURN_RIGHT: 'TURN_RIGHT',
    TURN_STRAIGHT: 'TURN_STRAIGHT',
    SET_SWITCH: 'SET_SWITCH',
    CLEAR_SWITCH:'CLEAR_SWITCH',
    TOGGLE_SWITCH: 'TOGGLE_SWITCH',
    TOGGLE_DIRECTION: 'TOGGLE_DIRECTION'
}