
export default {
    SET_DIRECTION_FORWARD: 'SET_DIRECTION_FORWARD',
    SET_DIRECTION_REVERSE: 'SET_DIRECTION_REVERSE',
    SET_THROTTLE: 'SET_THROTTLE',
    SET_THROTTLE_ZERO: 'SET_THROTTLE_ZERO',
    TURN_LEFT: 'TURN_LEFT',
    TURN_RIGHT: 'TURN_RIGHT',
    TURN_STRAIGHT: 'TURN_STRAIGHT',
    SET_SWITCH: 'SET_SWITCH',
    CLEAR_SWITCH:'CLEAR_SWITCH',
    TOGGLE_SWITCH: 'TOGGLE_SWITCH'
}