export const GET_POWER = 'GET_POWER'
export const SET_POWER = 'SET_POWER'
export const SET_POWER_OFF = 'SET_POWER_OFF'
export const ADJUST_SPEED = 'ADJUST_SPEED'
export const ADJUST_DIRECTION = 'ADJUST_DIRECTION'

export const GET_TURN = 'GET_TURN'
export const SET_TURN = 'SET_TURN'
export const SET_TURN_OFF = 'SET_TURN_OFF'
export const ADJUST_TURN = 'ADJUST_TURN'

export const SWITCH_ON = 'SWITCH_ON'
export const SWITCH_OFF = 'SWITCH_OFF'
export const TOGGLE_SWITCH = 'TOGGLE_SWITCH'
export const GET_SWITCH = 'GET_SWITCH'